config/routes.rb
Rails.application.routes.draw do
  resources :urls

  root 'urls#index'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @input_url = params[:input]
    puts @input_url
    client = Bitly.client
    if @input_url.length == 0
      puts "You have not entered anything."
      flash[:notice] = "You have not entered anything."
      redirect_to urls_path
    else
      @output_url = client.shorten(params[:input])
      puts "the short url is #{@output_url}"
    end

  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:input_url, :output_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortening</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>

<br><br>
<center><h1>Welcome to Awesome URL Generator</h1>
<br><br>

<%= form_tag(controller: "urls", action: "create", method: "post") do %>
  <%= label_tag(:input, "Enter the longer URL:") %>
  <%= text_field_tag(:input) %>
  <%= submit_tag("Submit") %>
<% end %>
<br>

app/views/urls/create.html.erb
<br><br>
<center>
<h3>Your url for <%= @output_url.long_url %> is: </h3>
<br><br>
<%= link_to @output_url.short_url, @output_url.short_url, target: "_blank" %><br /><br />
<br><br>
<%= link_to "Create another Url", root_path %>
</center>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<%= render 'form' %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input url:</strong>
  <%= @url.input_url %>
</p>

<p>
  <strong>Output url:</strong>
  <%= @url.output_url %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>